AE-2147: Add warning to käytönvalvonta toimenpide creation after reopening the valvonta
solita/ara-etp pull request #202
Opened 2024-03-05 11:38 UTC by Juholei

2024-03-05 14:33 UTC, solita-juhohaa requested changes

2024-03-06 06:55 UTC, Juholei commented on e2e-tests/cypress/cypress/e2e/kaytonvalvonta/kaytonvalvonta.cy.js
> +  );
Lisäsin kaikkiin muihinkin containsia käyttäviin tarkastuksiin

2024-03-06 07:41 UTC, solita-juhohaa approved these changes

2024-03-06 09:13 UTC, muep approved these changes

2024-03-06 09:37 UTC, merged