Update dependency litepicker to v2
solita/ara-etp pull request #287
Opened 2024-04-02 05:48 UTC by etp-bot-mu

This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [litepicker](https://litepicker.com) ([source](https://togithub.com/wakirin/litepicker)) | dependencies | major | [`^1.5.7` -> `^2.0.0`](https://renovatebot.com/diffs/npm/litepicker/1.5.7/2.0.12) |

---

### Release Notes

<details>
<summary>wakirin/litepicker (litepicker)</summary>

### [`v2.0.12`](https://togithub.com/wakirin/litepicker/compare/2.0.11...2.0.12)

[Compare Source](https://togithub.com/wakirin/litepicker/compare/2.0.11...2.0.12)

### [`v2.0.11`](https://togithub.com/wakirin/litepicker/compare/2.0.10...2.0.11)

[Compare Source](https://togithub.com/wakirin/litepicker/compare/2.0.10...2.0.11)

### [`v2.0.10`](https://togithub.com/wakirin/litepicker/compare/2.0.9...2.0.10)

[Compare Source](https://togithub.com/wakirin/litepicker/compare/2.0.9...2.0.10)

### [`v2.0.9`](https://togithub.com/wakirin/litepicker/compare/2.0.8...2.0.9)

[Compare Source](https://togithub.com/wakirin/litepicker/compare/2.0.8...2.0.9)

### [`v2.0.8`](https://togithub.com/wakirin/litepicker/compare/2.0.7...2.0.8)

[Compare Source](https://togithub.com/wakirin/litepicker/compare/2.0.7...2.0.8)

### [`v2.0.7`](https://togithub.com/wakirin/litepicker/compare/2.0.6...2.0.7)

[Compare Source](https://togithub.com/wakirin/litepicker/compare/2.0.6...2.0.7)

### [`v2.0.6`](https://togithub.com/wakirin/litepicker/compare/2.0.5...2.0.6)

[Compare Source](https://togithub.com/wakirin/litepicker/compare/2.0.5...2.0.6)

### [`v2.0.5`](https://togithub.com/wakirin/litepicker/compare/2.0.4...2.0.5)

[Compare Source](https://togithub.com/wakirin/litepicker/compare/2.0.4...2.0.5)

### [`v2.0.4`](https://togithub.com/wakirin/litepicker/compare/2.0.3...2.0.4)

[Compare Source](https://togithub.com/wakirin/litepicker/compare/2.0.3...2.0.4)

### [`v2.0.3`](https://togithub.com/wakirin/litepicker/compare/2.0.2...2.0.3)

[Compare Source](https://togithub.com/wakirin/litepicker/compare/2.0.2...2.0.3)

### [`v2.0.2`](https://togithub.com/wakirin/litepicker/compare/2.0.1...2.0.2)

[Compare Source](https://togithub.com/wakirin/litepicker/compare/2.0.1...2.0.2)

### [`v2.0.1`](https://togithub.com/wakirin/litepicker/compare/2.0.0...2.0.1)

[Compare Source](https://togithub.com/wakirin/litepicker/compare/2.0.0...2.0.1)

### [`v2.0.0`](https://togithub.com/wakirin/litepicker/compare/v1.5.7...2.0.0)

[Compare Source](https://togithub.com/wakirin/litepicker/compare/v1.5.7...2.0.0)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

2024-04-02 06:40 UTC, solita-antti-mottonen commented
Päivämäärän vaihtaminen ei toimi. Tarvitaan lisää testejä

2024-04-02 11:38 UTC, solita-antti-mottonen requested changes
Silently fails on use

2024-04-08 13:04 UTC, Juholei commented on e2e-tests/cypress/cypress/e2e/kaytonvalvonta/kaytonvalvonta.cy.js
> +  it.only('date picking works', () => {
only

2024-04-08 13:06 UTC, Juholei commented on e2e-tests/cypress/cypress/e2e/kaytonvalvonta/kaytonvalvonta.cy.js
> +    cy.get('[data-cy="toimenpide-type-selection"]')
Tässä voisi varmaan käyttää meidän cy.selectInSelect-komentoa

2024-04-08 13:07 UTC, Juholei commented on e2e-tests/cypress/cypress/e2e/kaytonvalvonta/kaytonvalvonta.cy.js
> +    cy.get('[data-cy="toimenpide-type-selection"]')
Tässäkin voisi varmaan käyttää cy.selectInSelectiä

2024-04-09 05:43 UTC, solita-antti-mottonen commented on e2e-tests/cypress/cypress/e2e/kaytonvalvonta/kaytonvalvonta.cy.js
> +  it.only('date picking works', () => {
Tuo on kyllä naurettava ominaisuus että ainut tapa ajaa yksi testi on muuttaa koodia

2024-04-09 06:59 UTC, Juholei approved these changes

2024-04-09 07:12 UTC, merged